name: Test Log Analytics

logDirectory: /scratch/local/monthly/dteixeir/log-analytics/logs-2016/**

parquetFile: /scratch/local/weekly/dteixeir/logs/prk/apache-logs.parquet
    
botPattern: (.*)(?i)(bot|crawler|spider|pingdom|monitis|teoma|facebook|bing|yahoo|embedly|quora|outbrain|pinterest|vkshare|validator)(.*)

programPattern : (.*)(?i)(python|java|perl|wget|ruby|curl)(.*)

grokFormat: COMBINEDAPACHELOG

fileName: /home/dteixeir/log-analytics/log-uniprot/*

locationServiceUrl: http://localhost:8087/json/
