name: Bgee

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/bgee-logs/*

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/bgee-parquet/
