name: Cellosaurus

#Directory where to find the log files. Use a symbolic linnk
logDirectory: symbolic-link-to-log-directory/web-expasy.org/**

#Directory where to output or read the parquet file
parquetFile: symbolic-link-to-parquet-directory/cellosaurus

#The first level path filter
firstLevelPathFilter: /cellosaurus