name: Cellosaurus

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/expasy/web.cellosaurus.access-2017.log

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/cellosaurus-parquet
