name: Cellosaurus

#Directory where to find the log files
logDirectory: $LOG_DIRECTORY_BASE/web-expasy.org/**

#Directory where to output or read the parquet file
parquetFile: $PARQUET_DIRECTORY_BASE/parquet-logs/cellosaurus

#The first level path filter
firstLevelPathFilter: /cellosaurus
