name: Enzyme

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/expasy/enzyme/*

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/enzyme-parquet
