name: neXtProt

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/neXtProt-logs/www.nextprot.org/*

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/nextprot-parquet/
