name: Prosite

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/prosite-logs/**

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/prosite-parquet
