name: Test Log Analytics

#Directory where to find the log files
logDirectory: /scratch/cluster/monthly/dteixeir/impact-study-sample-data/www.ebi.ac.uk_http/pg-www-lb2/rhea-pg-www-lb2.logs

#Directory where to output or read the parquet file
parquetFile: /scratch/cluster/monthly/dteixeir/impact-study-sample-data/rhea-logs.parquet
