name: Rhea

#Directory where to find the log files
logDirectory: symbolic-link-to-log-directory/rhea/**

#Directory where to output or read the parquet file
parquetFile: symbolic-link-to-parquet-directory/rhea
