name: SwissDock

#Directory where to find the log files
logDirectory: symbolic-link-to-log-directory/swissdock/**

#Directory where to output or read the parquet file
parquetFile: symbolic-link-to-parquet-directory/swissdock
