name: UniCarbDB

#Directory where to find the log files
logDirectory: /scratch/local/weekly/dteixeir/unicarb-db-logs/**

#Directory where to output or read the parquet file
parquetFile: /scratch/local/weekly/dteixeir/unicarb-parquet
