name: UniProt

#Directory where to find the log files
logDirectory: /scratch/local/monthly/dteixeir/uniprot-logs/**

#Directory where to output or read the parquet file
parquetFile: /scratch/local/monthly/dteixeir/uniprot-parquet/
